---
title: "Heatmaps - CRC Batch 1"
author: Sophie Herbst
output:
  html_document:
    code_folding: hide
    toc: yes
    toc_depth: 4
    toc_float: yes
editor_options: 
  chunk_output_type: console
---
Analysis date: `r Sys.Date()`

# Depends on
DIPG_FirstBatch_DataProcessing Script

```{r}
load("../Data/Cache/Xenografts_Batch1_2_DataProcessing.RData")
```

# TODO

* Annotated sample prep batch in heatmap

# Setup
## Load libraries and functions
```{r, echo=FALSE, warning=FALSE, message=FALSE}
set.seed(2022)
library(fgsea)
library(AnnotationDbi)
library(org.Hs.eg.db)
library(DEP)
library(SummarizedExperiment)
# library(pls)
library(mdatools)
source("../../../General/Code/Analysis_Functions.R")
source("CRC_Xenografts_Batch1_Functions.R")
```

# Analysis
## Heatmaps log2 fold change normalised to ctrl
### Phospho-Tyrosines 
#### Clustered
```{r, fig.height=8, fig.width=10}
pY_mat_Set1 %>% 
  pheatmap::pheatmap(col = colorRampPalette(c("navy", "white", "firebrick3"))(50), 
                     labels_row = sub("log2FC_Xenograft_", "", rownames( pY_mat_Set1 )),  
                     show_colnames = FALSE,
                     #scale = "column"  
                     )
```

## With missing values
```{r}
pY_NAs %>%
  mutate(namepep= paste0(HGNC_Symbol, "_", `Annotated Sequence`)) %>%
  select(-c("Sequence", "Annotated Sequence", "Master Protein Accessions", "Master Protein Descriptions", "HGNC_Symbol") ) %>% 
  pivot_longer(-namepep, names_to = "sample") %>%
  mutate(log2value = log2(value)) %>%
  ggplot(aes(sample, namepep, fill = log2value)) +
  geom_tile() +
  theme(axis.text.x = element_text(angle = 90)) +
  scale_fill_continuous(type = "viridis")
```


```{r}
pY_NAs %>%
  filter(HGNC_Symbol=="EGFR") 

pY_NAs %>% filter(HGNC_Symbol == "PDGFRA")
pY_NAs %>% filter(HGNC_Symbol == "PDGFRB")

#pST_NAs %>%
#  filter(HGNC_Symbol=="EGFR")
```

# Session Info
```{r}
sessionInfo()
knitr::knit_exit()
```
