---
title: "Quality control - Distributions - CRC Batch 2 Set 4"
author: Sophie Herbst
output:
  html_document:
    code_folding: hide
    toc: yes
    toc_depth: 4
    toc_float: yes
editor_options: 
  chunk_output_type: console
---
Analysis date: `r Sys.Date()`

# Depends on
CRC_Xenografts_Batch2_DataProcessing Script

```{r}
load("../Data/Cache/Xenografts_Batch2_DataProcessing.RData")
```



# Setup
## Load libraries and functions
```{r, echo=FALSE, warning=FALSE, message=FALSE}
set.seed(2022)
library(fgsea)
library(AnnotationDbi)
library(org.Hs.eg.db)
library(DEP)
library(SummarizedExperiment)
# library(pls)
library(mdatools)
source("../../../General/Code/Analysis_Functions.R")
source("CRC_Xenografts_Batch2_Functions.R")
```

# Quality control
## Nr. phospho sites
```{r}
print( paste( nrow(pY_Set4_form) , "pY peptides passed the filtering procedure for this Set. These peptides were detected from", length(unique(pY_Set4_form$HGNC_Symbol) ), "proteins." ))
print( paste( nrow(pST_Set4_form) , "pY peptides passed the filtering procedure for this Set. These peptides were detected from", length(unique(pST_Set4_form$HGNC_Symbol) ), "proteins." ))
```

## Distributions
### pY Abundances
#### Colored by treatment
```{r}
pY_Set4_form %>%
  select(contains("log2FC")) %>%
  pivot_longer(names_to = "Sample", cols = everything()) %>%
  mutate(Sample = str_remove(Sample, "log2FC_"), drop = F) %>%
  separate( Sample , into = c("xenograft", "treatment", "day", "replicate", "set"), sep = "_", remove = F) %>%
  mutate(treatment=as.factor(treatment)) %>%
  mutate(treatment=factor(treatment, levels =  c( "ctrl", "E", "EC", "EBC") )) %>%
  ggplot(aes(value, fill= treatment, group = Sample)) +
  #geom_histogram(bins= 200) +
  geom_density(alpha=0.5) +
  ggtitle("log2FC") +
  theme_bw() +
  scale_fill_manual(values = PGPalette[c(5, 1, 2, 4)])

pY_Set4_form %>%
  select(contains("log2FC")) %>%
  pivot_longer(names_to = "Sample", cols = everything()) %>%
  mutate(Sample = str_remove(Sample, "log2FC_")) %>%
  separate( Sample , into = c( "xenograft", "treatment", "day", "replicate", "set"), sep = "_", remove = F) %>%
  mutate(treatment=as.factor(treatment)) %>%
  mutate(treatment=factor(treatment, levels =  c( "ctrl", "E", "EC", "EBC") )) %>%
  ggplot(aes(Sample, value, fill= treatment)) +
  geom_boxplot() +
  ggtitle("log2FC") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90)) +
  scale_fill_manual(values = PGPalette[c(5, 1, 2, 4)])

pY_Set4_form %>%
  select(contains("log2FC")) %>%
  pivot_longer(names_to = "Sample", cols = everything()) %>%
  mutate(Sample = str_remove(Sample, "log2FC_")) %>%
  separate( Sample , into = c( "xenograft", "treatment", "day", "replicate", "set"), sep = "_", remove = F) %>%
  mutate(treatment=as.factor(treatment)) %>%
  mutate(treatment=factor(treatment, levels =  c( "ctrl", "E", "EC", "EBC") )) %>%
  group_by(Sample, treatment, day, replicate, set) %>%
  summarise(mean_value = mean(value)) %>%
  ggplot(aes(treatment, mean_value, fill= treatment)) +
  geom_boxplot() +
  ggbeeswarm::geom_beeswarm() +
  ggtitle("log2FC") +
  ggpubr::stat_compare_means() +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90)) +
  scale_fill_manual(values = PGPalette[c(5, 1, 2, 4)])
```

### pST Abundances
#### Colored by treatment
```{r}
pST_Set4_form %>%
  select(contains("log2FC")) %>%
  pivot_longer(names_to = "Sample", cols = everything()) %>%
  mutate(Sample = str_remove(Sample, "log2FC_"), drop = F) %>%
  separate( Sample , into = c("xenograft", "treatment", "day", "replicate", "set"), sep = "_", remove = F) %>%
  mutate(treatment=as.factor(treatment)) %>%
  mutate(treatment=factor(treatment, levels =  c( "ctrl", "E", "EC", "EBC") )) %>%
  ggplot(aes(value, fill= treatment, group = Sample)) +
  #geom_histogram(bins= 200) +
  geom_density(alpha=0.5) +
  ggtitle("log2FC") +
  theme_bw() +
  scale_fill_manual(values = PGPalette[c(5, 1, 2, 4)])

pST_Set4_form %>%
  select(contains("log2FC")) %>%
  pivot_longer(names_to = "Sample", cols = everything()) %>%
  mutate(Sample = str_remove(Sample, "log2FC_")) %>%
  separate( Sample , into = c( "xenograft", "treatment", "day", "replicate", "set"), sep = "_", remove = F) %>%
  mutate(treatment=as.factor(treatment)) %>%
  mutate(treatment=factor(treatment, levels =  c( "ctrl", "E", "EC", "EBC") )) %>%
  ggplot(aes(Sample, value, fill= treatment)) +
  geom_boxplot() +
  ggtitle("log2FC") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90)) +
  scale_fill_manual(values = PGPalette[c(5, 1, 2, 4)])

pST_Set4_form %>%
  select(contains("log2FC")) %>%
  pivot_longer(names_to = "Sample", cols = everything()) %>%
  mutate(Sample = str_remove(Sample, "log2FC_")) %>%
  separate( Sample , into = c( "xenograft", "treatment", "day", "replicate", "set"), sep = "_", remove = F) %>%
  mutate(treatment=as.factor(treatment)) %>%
  mutate(treatment=factor(treatment, levels =  c( "ctrl", "E", "EC", "EBC") )) %>%
  group_by(Sample, treatment, day, replicate, set) %>%
  summarise(mean_value = mean(value)) %>%
  ggplot(aes(treatment, mean_value, fill= treatment)) +
  geom_boxplot() +
  ggbeeswarm::geom_beeswarm() +
  ggtitle("log2FC") +
  ggpubr::stat_compare_means() +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90)) +
  scale_fill_manual(values = PGPalette[c(5, 1, 2, 4)])
```


# Session Info
```{r}
sessionInfo()
knitr::knit_exit()
```
