---
title: "Plotting individual peptides - DIPG Batch 1"
author: Sophie Herbst
output:
  html_document:
    code_folding: hide
    toc: yes
    toc_depth: 4
    toc_float: yes
editor_options: 
  chunk_output_type: console
---
Analysis date: `r Sys.Date()`

# Depends on
DIPG_FirstBatch_DataProcessing Script

```{r}
load("../Data/Cache/Xenografts_Batch1_DataProcessing.RData")
```

# TODO

# Setup
## Load libraries and functions
```{r, echo=FALSE, warning=FALSE, message=FALSE}
set.seed(2022)
library(fgsea)
library(AnnotationDbi)
library(org.Hs.eg.db)
library(DEP)
library(SummarizedExperiment)
# library(pls)
library(mdatools)
source("../../../General/Code/Analysis_Functions.R")
source("CRC_Xenografts_Batch1_Functions.R")
```

# Barplots

## Individual peptides
### Cherry picked
```{r}
plot_barplot_phos( dat= pY_noNA, prot = "RET", add_title = "pY" )
plot_boxplot_phos( dat= pY_noNA, prot = "RET", add_title = "pY" , specific_peptide = "RRDyLDLAASTPSDSLIYDDGLSEEETPLVDCNNAPLPR")
plot_barplot_phos( dat= pY_noNA, prot = "MAPK1", add_title = "pY" )
plot_barplot_phos( dat= pY_noNA, prot = "MAPK3", add_title = "pY" )
plot_barplot_phos( dat= pY_noNA, prot = "BCAR1", add_title = "pY" )
plot_boxplot_phos( dat= pY_noNA, prot = "BCAR1", add_title = "pY" , specific_peptide = "HLLAPGPQDIyDVPPVR")
plot_barplot_phos( dat= pY_noNA, prot = "LYN", add_title = "pY" )
plot_boxplot_phos( dat= pY_noNA, prot = "LYN", add_title = "pY" , specific_peptide = "AEERPTFDYLQSVLDDFyTATEGQYQQQP")
plot_barplot_phos( dat= pY_noNA, prot = "MAPK3", add_title = "pY" )
plot_boxplot_phos( dat= pY_noNA, prot = "MAPK3", add_title = "pY" , specific_peptide = "IADPEHDHTGFLTEyVATR")
plot_barplot_phos( dat= pY_noNA, prot = "MAPK1", add_title = "pY" )
plot_boxplot_phos( dat= pY_noNA, prot = "MAPK1", add_title = "pY" , specific_peptide = "VADPDHDHTGFLTEyVATR")
plot_barplot_phos( dat= pY_noNA, prot = "DDR1", add_title = "pY" )
#plot_boxplot_phos( dat= pY_noNA, prot = "DDR1", add_title = "pY" , specific_peptide = "")
```

# Session Info
```{r}
sessionInfo()
knitr::knit_exit()
```
