---
title: "Quality control PCA- CRC Batch 1"
author: Sophie Herbst
output:
  html_document:
    code_folding: hide
    toc: yes
    toc_depth: 4
    toc_float: yes
editor_options: 
  chunk_output_type: console
---
Analysis date: `r Sys.Date()`

# Depends on
CRC_Xenografts_FirstBatch_DataProcessing Script  
CRC_Xenografts_Batch1_SOMs_mediancenter Script

```{r}
load("../Data/Cache/Xenografts_Batch1_DataProcessing.RData")
```

# TODO

# Setup
## Load libraries and functions
```{r, echo=FALSE, warning=FALSE, message=FALSE}
set.seed(2022)
library(fgsea)
library(AnnotationDbi)
library(org.Hs.eg.db)
library(DEP)
library(SummarizedExperiment)
# library(pls)
library(mdatools)
source("../../../General/Code/Analysis_Functions.R")
source("CRC_Xenografts_Batch1_Functions.R")
```

```{r}
SOMsk13 <- read_delim("../Data/ForCollaborators/Xenografts_Batch1_k13pY.txt", delim = " ")
excl_peptides <- SOMsk13 %>% filter(cluster %in% c(3,4,5,8) ) %>% .$Annotated_Sequence

excl_H_peptides <- SOMsk13 %>% filter(cluster %in% c(3,4,5,8) ) %>%
  mutate(peptide = paste0( HGNC_Symbol, "_", Annotated_Sequence) ) %>%
  .$peptide
```

# Quality control
## Nr. phospho sites
```{r}
print( paste( nrow(pY_Set1 %>% filter(! `Annotated Sequence` %in% excl_peptides )) , "pY peptides passed the filtering procedure for Set 1. " ))
#print( paste( nrow(pST_Set1) , "pST peptides passed the filtering procedure for Set 1. These peptides were detected from", length(unique(pST$HGNC_Symbol) ), "proteins." ))

print( paste( nrow(pY_Set2 %>% filter(! `Annotated Sequence` %in% excl_peptides )) , "pY peptides passed the filtering procedure for Set 2. " ))
#print( paste( nrow(pST_Set2) , "pST peptides passed the filtering procedure for Set 2. These peptides were detected from", length(unique(pST$HGNC_Symbol) ), "proteins." ))

print( paste( nrow(pY_Set3 %>% filter(! `Annotated Sequence` %in% excl_peptides )) , "pY peptides passed the filtering procedure for Set 3." ))
#print( paste( nrow(pST_Set3) , "pST peptides passed the filtering procedure for Set 3. These peptides were detected from", length(unique(pST$HGNC_Symbol) ), "proteins." ))

print( paste( nrow(pY_noNA  %>% filter(! Annotated_Sequence %in% excl_peptides) ) , "pY peptides passed the filtering procedure for the sets combined." ))
#print( paste( nrow(pST_noNA) , "pST peptides passed the filtering procedure for the sets combined. These peptides were detected from", length(unique(pST_noNA$HGNC_Symbol) ), "proteins." ))
```

## Principle component analysis
### Phospho-Tyrosines
```{r, fig.width=3, fig.height=3}
kept_h_pept <- !colnames(pY_mat) %in% excl_H_peptides

pY_mat[,kept_h_pept] %>%
  prcomp() %>% 
  summary() %>% 
  .$importance %>% t() %>% as.data.frame() %>%
  rownames_to_column("PC") %>% 
  as_tibble() %>%
  mutate(PC = as.factor(PC)) %>%
  mutate(PC = factor(PC, levels = PC)) %>%
  ggplot(aes(PC, `Proportion of Variance` )) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 90))
```

```{r, fig.width=9, fig.height=3}
PCA_pY <- pY_mat[,kept_h_pept] %>%
  prcomp() %>% 
  .$x %>% 
  as.data.frame() %>%
  rownames_to_column("sample")

PCApY_rot <- pY_mat[,kept_h_pept] %>%
  prcomp() %>%
  .$rotation
PCApY_rot <- bind_cols(PCApY_rot, 
  (pY_noNA %>% filter(! Annotated_Sequence %in% excl_peptides) %>% select(HGNC_Symbol, Annotated_Sequence) ) ) %>% arrange(desc(PC1) )

PCA_pY$prep <- unlist(prep_l[gsub( "log2FC_", "", PCA_pY$sample )])
PCA_pY$seppack <- unlist(seppack_l[gsub( "log2FC_", "", PCA_pY$sample )]) 

PCA_pY <- PCA_pY %>% 
  separate( sample , into = c("log2FC", "xenograft", "treatment", "day", "replicate", "set"), sep = "_")

PCA12_pY <- PCA_pY %>% 
  ggplot(aes(PC1, PC2, color = treatment, shape = day )) +
  geom_point(size = 3) +
  theme_classic() +
  #scale_colour_manual(values=PGPalette[c(1,5)]) +
  #geom_text(aes(label = replicate), color = "black", nudge_x = 1) +
  ggtitle("pY")

PCA34_pY <- PCA_pY %>% 
  ggplot(aes(PC3, PC4, color = treatment, shape = day )) +
  geom_point(size = 3) +
  theme_classic() +
  #scale_colour_manual(values=PGPalette[c(1,5)]) +
  #geom_text(aes(label = replicate), color = "black", nudge_x = 1) +
  ggtitle("pY")

ggpubr::ggarrange(PCA12_pY, PCA34_pY)

PCA12_pY <- PCA_pY %>% 
  ggplot(aes(PC1, PC2, color = prep, shape = seppack )) +
  geom_point(size = 3) +
  theme_classic() +
  #scale_colour_manual(values=PGPalette[c(1,5)]) +
  #geom_text(aes(label = replicate), color = "black", nudge_x = 1) +
  ggtitle("pY")

PCA34_pY <- PCA_pY %>% 
  ggplot(aes(PC3, PC4, color = prep, shape = seppack )) +
  geom_point(size = 3) +
  theme_classic() +
  #scale_colour_manual(values=PGPalette[c(1,5)]) +
  #geom_text(aes(label = replicate), color = "black", nudge_x = 1) +
  ggtitle("pY")

ggpubr::ggarrange(PCA12_pY, PCA34_pY)

PCA12_pY <- PCA_pY %>% 
  ggplot(aes(PC1, PC2, color = set, shape = prep )) +
  geom_point(size = 3) +
  theme_classic() +
  #scale_colour_manual(values=PGPalette[c(1,5)]) +
  #geom_text(aes(label = replicate), color = "black", nudge_x = 1) +
  ggtitle("pY")

PCA34_pY <- PCA_pY %>% 
  ggplot(aes(PC3, PC4, color = set, shape = prep )) +
  geom_point(size = 3) +
  theme_classic() +
  #scale_colour_manual(values=PGPalette[c(1,5)]) +
  #geom_text(aes(label = replicate), color = "black", nudge_x = 1) +
  ggtitle("pY")

ggpubr::ggarrange(PCA12_pY, PCA34_pY)
```

These are the weights of the peptides loaded onto the principle components:

```{r, fig.width=4, fig.height=3, eval=TRUE}
PCcolspY <- match(  c("HGNC_Symbol", "PC1", "PC2", "PC3", "PC4", "Annotated_Sequence") , colnames(PCApY_rot))
DT::datatable( PCApY_rot[,PCcolspY], 
              class = 'cell-border stripe', rownames = FALSE) %>% 
  DT::formatRound(c('PC1', 'PC2', 'PC3', 'PC4'), 3)
```

# Session Info
```{r}
sessionInfo()
knitr::knit_exit()
```
